import 'dart:convert';
import 'dart:math';

import 'package:flutter/widgets.dart';
import 'package:http/http.dart' as http;
import 'package:shop_app/models/product.dart';

class ProductList with ChangeNotifier {
  final _url =
      'https://shop-app-3e7fa-default-rtdb.firebaseio.com/products.json';
  final List<Product> _items = [];

  bool _showFavoritesOnly = false;

  List<Product> get items {
    if (_showFavoritesOnly) {
      return _items.where((prod) => prod.isFavorite).toList();
    } else {
      return [..._items];
    }
  }

  void showFavoritesOnly() {
    _showFavoritesOnly = true;
    notifyListeners(); // Notify listeners about the change to the product list and update the UI accordingly.
  }

  void showAll() {
    _showFavoritesOnly = false;

    notifyListeners(); // Notify listeners about the change to the product list and update the UI accordingly.
  }

  Future<void> saveProduct(Map<String, Object> data) {
    bool hasId = data['id'] != null;

    final product = Product(
      id: hasId ? data['id'] as String : Random().nextDouble().toString(),
      name: data['name'] as String,
      description: data['description'] as String,
      price: data['price'] as double,
      imageUrl: data['imageUrl'] as String,
    );

    if (hasId) {
      return updateProduct(product);
    } else {
      return addProduct(product);
    }
    // Notify listeners about the change to the product list and update the UI accordingly.
  }

  Future<void> addProduct(Product product) async {
    //async indicates that this function performs asynchronous operations
    final response = await http.post(
      //await waits for the HTTP POST request to complete
      Uri.parse(_url),
      body: jsonEncode({
        'name': product.name,
        'description': product.description,
        'price': product.price,
        'imageUrl': product.imageUrl,
        'isFavorite': product.isFavorite,
      }),
    );

    //we don't need return here because the function is declared as Future<void>

    final id = jsonDecode(
      response.body,
    )['name']; // Extract the generated ID from the response.
    _items.add(
      Product(
        id: id, //this id is generated by Firebase
        name: product.name,
        description: product.description,
        price: product.price,
        imageUrl: product.imageUrl,
      ),
    );
    notifyListeners();
  }

  Future<void> updateProduct(Product product) {
    int index = _items.indexWhere((p) => p.id == product.id);
    if (index >= 0) {
      _items[index] = product;
      notifyListeners();
    }

    return Future.value();
  }

  void removeProduct(Product product) {
    int index = _items.indexWhere((p) => p.id == product.id);
    if (index >= 0) {
      _items.removeWhere((p) => p.id == product.id);
      notifyListeners();
    }
  }

  int get itemsCount {
    return _items.length;
  }

  Future<void> loadProducts() async {
    final response = await http.get(Uri.parse(_url));
    Map<String, dynamic>? data = jsonDecode(response.body);

    if (data == null) {
      //this if is used to handle the case when there are no products in the database
      return;
    }

    _items.clear(); // Clear the existing list before loading new products

    data.forEach((productId, productData) {
      _items.add(
        Product(
          id: productId,
          name: productData['name'],
          description: productData['description'],
          price: productData['price'],
          imageUrl: productData['imageUrl'],
          isFavorite: productData['isFavorite'],
        ),
      );
    });

    notifyListeners();
  }
}
